"""Resolve and hash all install artifacts using the target Python interpreter.

Run in the pinned Linux Python image. Locks intentionally target Linux x86-64;
refresh them explicitly after reviewing dependency updates.
"""

import argparse
import hashlib
import subprocess
import sys
import tempfile
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    with tempfile.TemporaryDirectory() as directory:
        subprocess.run([sys.executable, "-m", "pip", "download", "--only-binary=:all:",
                        "--dest", directory, "-r", str(args.source)], check=True)
        lines = ["# Generated by scripts/lock_dependencies.py on Linux x86-64, Python 3.12.",
                 "# Review and regenerate; do not edit individual artifact hashes."]
        for wheel in sorted(Path(directory).glob("*.whl")):
            name, version = wheel.name.split("-")[:2]
            digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
            lines.append(f"{name}=={version} --hash=sha256:{digest}")
        args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
